domain: agkrl.github.io
title: Тайтл
email: agafonovkirill.57@yandex.ru
lang: 'ru-RU'
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
keywords: 'key key key'
baseurl: '/agkrl'
url: 'https://agkrl.github.io/agkrl'
twitter_username: agkirill
github_username: agkrl

collections:
  projects:
    permalink: /:collection/:path
    output: true

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - tailwind.config.js
  - package.json
  - package-lock.json
  - postcss.config.js
  - assets/
  - gulpfile.js
  - Dockerfile
  - install.sh
  - install-local.sh
